// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5IDypt35ugmsN22SGL7cCep0tReOCiAw',
    appId: '1:677642996279:web:2c0d5ac62e5f2a2428cdb2',
    messagingSenderId: '677642996279',
    projectId: 'online-learning-app-3d4be',
    authDomain: 'online-learning-app-3d4be.firebaseapp.com',
    storageBucket: 'online-learning-app-3d4be.appspot.com',
    measurementId: 'G-06S17ZDD5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN0zmaY0YFMuoeanxM1fdlVVt0xSZQBKs',
    appId: '1:677642996279:android:2dd0b428aea93f9b28cdb2',
    messagingSenderId: '677642996279',
    projectId: 'online-learning-app-3d4be',
    storageBucket: 'online-learning-app-3d4be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg58yZUPsf_JVaP2vES3iFzV1jNzRCXKg',
    appId: '1:677642996279:ios:838778b9c0567fe828cdb2',
    messagingSenderId: '677642996279',
    projectId: 'online-learning-app-3d4be',
    storageBucket: 'online-learning-app-3d4be.appspot.com',
    iosBundleId: 'com.example.onlineLearningApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg58yZUPsf_JVaP2vES3iFzV1jNzRCXKg',
    appId: '1:677642996279:ios:838778b9c0567fe828cdb2',
    messagingSenderId: '677642996279',
    projectId: 'online-learning-app-3d4be',
    storageBucket: 'online-learning-app-3d4be.appspot.com',
    iosBundleId: 'com.example.onlineLearningApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5IDypt35ugmsN22SGL7cCep0tReOCiAw',
    appId: '1:677642996279:web:5944d0fb87cdc30d28cdb2',
    messagingSenderId: '677642996279',
    projectId: 'online-learning-app-3d4be',
    authDomain: 'online-learning-app-3d4be.firebaseapp.com',
    storageBucket: 'online-learning-app-3d4be.appspot.com',
    measurementId: 'G-4X5Y4TVP8J',
  );
}
